spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/com_jiang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '0706'
    #url: jdbc:mysql://192.168.0.103/addressbook?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /addressbook
mybatis:
  type-aliases-package: com.baldgroup.addressbook.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
